services:

  frontend:
    build: ./frontend
    container_name: taskhub-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: taskhub-backend
    ports:
      - "8000:8000"

    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}